# Model configuration
model:
  model_id: "Qwen/Qwen2.5-Omni-3B"
  freeze_text_model: false
  audio_layer: -1
  bidirectional_audio: true
  linear_bias: 0
  dtype: "auto"

# Training configuration
training:
  epochs: 3
  effective_batch_size: 8
  learning_rate: 1.0e-6
  eta_min_scale: 1.0
  
# Dataset configuration
dataset:
  split: "train"
  repository: "enyoukai/AudioSet-Strong-Human-Sounds"

task:
  type: "SINGLE_WORD_TIMESTAMP_ANY"
  kwargs:
    key: "start"

# Loss configuration
loss:
  token_loss: true
  surrogate_loss: false
  surrogate_loss_weight: 0.0
  class_weighting: false
  poisson_loss: false

# System configuration
system:
  dataloader_num_workers: 1
  seed: 80

# Wandb configuration
wandb:
  entity: "taudio"